In [17]:
from mytoolbox import *
import mytoolbox.PyDataFrame as df

In [14]:
import mytoolbox
help(mytoolbox)

Help on package mytoolbox:

NAME
    mytoolbox - # from .interpolation import *

PACKAGE CONTENTS
    PyDataFrame
    data_frame
    interpolation
    interpolation_bindings
    testing_interpolation

FILE
    /home/giovanni/miniconda3/lib/python3.12/site-packages/mytoolbox/__init__.py

In [22]:
iris = df.DataFrame()

In [24]:
iris.read_csv('../datasets/iris.csv')

In [25]:
iris.to_pandas()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,NaN,1.4,0.2,Iris-setosa
1,2.0,4.9,3.0,1.4,0.2,Iris-setosa
2,3.0,4.7,3.2,1.3,NaN,Iris-setosa
3,4.0,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica